name: build-sign-push
on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - .github/workflows/build-sign-push.yml
  workflow_dispatch:

env:
  IMAGE: docker.io/naveenbana5250/signed-demo

permissions:
  contents: read

jobs:
  build-sign-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check required secrets
        run: |
          [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] || { echo "Missing DOCKERHUB_USERNAME"; exit 1; }
          [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]    || { echo "Missing DOCKERHUB_TOKEN"; exit 1; }
          [ -n "${{ secrets.COSIGN_PRIVATE_KEY }}" ] || { echo "Missing COSIGN_PRIVATE_KEY"; exit 1; }
          [ -n "${{ secrets.COSIGN_PASSWORD }}" ]    || { echo "Missing COSIGN_PASSWORD"; exit 1; }

      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=demo
            type=sha,format=long

      - id: build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: sigstore/cosign-installer@v3.7.0

      - name: Write cosign key (PEM)
        run: |
          printf -- '%s' "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          chmod 600 cosign.key

      - name: Sign by digest
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --yes --key cosign.key ${IMAGE}@${{ steps.build.outputs.digest }}
