name: Build, Push, and Sign

on:
  push:
    branches: [ main ]

jobs:
  build-push-sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image name
        run: echo "IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/myapp" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ github.sha }}
          provenance: false

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Write cosign key
        run: |
          printf "%s" "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key

      - name: Sign image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --key cosign.key ${{ env.IMAGE }}:${{ github.sha }}

      - name: Print digest
        run: echo "DIGEST=${{ steps.build.outputs.digest }}"
