name: Build, Push & Sign Docker Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-sign-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        run: |
          IMAGE=docker.io/${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Install Cosign
        run: |
          wget https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-linux-amd64 -O cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/

      - name: Restore cosign.key from secret
        run: echo "${{ secrets.COSIGN_KEY }}" > cosign.key

      - name: Sign the image with Cosign (keyed, not keyless)
        run: |
          echo "${{ secrets.COSIGN_PASSWORD }}" | cosign sign --key cosign.key ${{ env.IMAGE }}
